# Expansión masiva de productos para análisis completo
EXPANDED_PRODUCTS = {
    # LÁCTEOS Y DERIVADOS (15 productos)
    'leche_entera_1L': 'Leche, lácteos y huevos',
    'leche_descremada_1L': 'Leche, lácteos y huevos',
    'leche_chocolatada_1L': 'Leche, lácteos y huevos',
    'yogur_natural_1kg': 'Leche, lácteos y huevos',
    'yogur_bebible_1L': 'Leche, lácteos y huevos',
    'yogur_griego_150g': 'Leche, lácteos y huevos',
    'manteca_200g': 'Leche, lácteos y huevos',
    'margarina_250g': 'Leche, lácteos y huevos',
    'queso_cremoso_kg': 'Leche, lácteos y huevos',
    'queso_rallado_100g': 'Leche, lácteos y huevos',
    'queso_mozzarella_kg': 'Leche, lácteos y huevos',
    'queso_provoleta_kg': 'Leche, lácteos y huevos',
    'dulce_leche_400g': 'Leche, lácteos y huevos',
    'crema_leche_200ml': 'Leche, lácteos y huevos',
    'huevos_docena': 'Leche, lácteos y huevos',
    
    # PANADERÍA Y CEREALES (18 productos)
    'pan_lactal_500g': 'Pan y cereales',
    'pan_frances_kg': 'Pan y cereales',
    'pan_integral_500g': 'Pan y cereales',
    'facturas_6_unidades': 'Pan y cereales',
    'medialunas_6_unidades': 'Pan y cereales',
    'galletitas_dulces_300g': 'Pan y cereales',
    'galletitas_saladas_300g': 'Pan y cereales',
    'galletitas_agua_300g': 'Pan y cereales',
    'tostadas_200g': 'Pan y cereales',
    'cereales_400g': 'Pan y cereales',
    'avena_500g': 'Pan y cereales',
    'granola_400g': 'Pan y cereales',
    'bizcochos_300g': 'Pan y cereales',
    'alfajores_6_unidades': 'Pan y cereales',
    'barras_cereal_6_unidades': 'Pan y cereales',
    'copos_maiz_300g': 'Pan y cereales',
    'salvado_avena_200g': 'Pan y cereales',
    'premezcla_panqueques_500g': 'Pan y cereales',
    
    # CARNES Y PROTEÍNAS (20 productos)
    'carne_picada_kg': 'Carnes',
    'asado_kg': 'Carnes',
    'bife_chorizo_kg': 'Carnes',
    'nalga_kg': 'Carnes',
    'paleta_kg': 'Carnes',
    'costilla_kg': 'Carnes',
    'matambre_kg': 'Carnes',
    'pollo_entero_kg': 'Carnes',
    'pechuga_pollo_kg': 'Carnes',
    'muslo_pollo_kg': 'Carnes',
    'milanesas_pollo_kg': 'Carnes',
    'milanesas_carne_kg': 'Carnes',
    'chorizo_kg': 'Carnes',
    'morcilla_kg': 'Carnes',
    'salchichas_kg': 'Carnes',
    'jamon_cocido_kg': 'Carnes',
    'salame_kg': 'Carnes',
    'mortadela_kg': 'Carnes',
    'bondiola_kg': 'Carnes',
    'panceta_kg': 'Carnes',
    
    # PESCADOS Y MARISCOS (12 productos)
    'merluza_kg': 'Pescados y mariscos',
    'salmon_kg': 'Pescados y mariscos',
    'atun_lata_170g': 'Pescados y mariscos',
    'sardinas_lata_125g': 'Pescados y mariscos',
    'caballa_lata_125g': 'Pescados y mariscos',
    'corvina_kg': 'Pescados y mariscos',
    'lenguado_kg': 'Pescados y mariscos',
    'camarones_kg': 'Pescados y mariscos',
    'mejillones_kg': 'Pescados y mariscos',
    'calamar_kg': 'Pescados y mariscos',
    'pulpo_kg': 'Pescados y mariscos',
    'bacalao_kg': 'Pescados y mariscos',
    
    # FRUTAS Y VERDURAS (25 productos)
    'tomate_kg': 'Frutas y verduras',
    'papa_kg': 'Frutas y verduras',
    'cebolla_kg': 'Frutas y verduras',
    'zanahoria_kg': 'Frutas y verduras',
    'lechuga_unidad': 'Frutas y verduras',
    'apio_kg': 'Frutas y verduras',
    'zapallo_kg': 'Frutas y verduras',
    'calabaza_kg': 'Frutas y verduras',
    'berenjena_kg': 'Frutas y verduras',
    'pimiento_kg': 'Frutas y verduras',
    'choclo_unidad': 'Frutas y verduras',
    'broccoli_kg': 'Frutas y verduras',
    'coliflor_kg': 'Frutas y verduras',
    'banana_kg': 'Frutas y verduras',
    'manzana_kg': 'Frutas y verduras',
    'naranja_kg': 'Frutas y verduras',
    'limon_kg': 'Frutas y verduras',
    'pera_kg': 'Frutas y verduras',
    'durazno_kg': 'Frutas y verduras',
    'uva_kg': 'Frutas y verduras',
    'frutilla_500g': 'Frutas y verduras',
    'kiwi_kg': 'Frutas y verduras',
    'palta_unidad': 'Frutas y verduras',
    'ananá_unidad': 'Frutas y verduras',
    'sandia_kg': 'Frutas y verduras',
    
    # ALMACÉN Y DESPENSA (22 productos)
    'arroz_1kg': 'Alimentos y bebidas no alcohólicas',
    'fideos_500g': 'Alimentos y bebidas no alcohólicas',
    'fideos_integrales_500g': 'Alimentos y bebidas no alcohólicas',
    'ñoquis_500g': 'Alimentos y bebidas no alcohólicas',
    'aceite_900ml': 'Alimentos y bebidas no alcohólicas',
    'aceite_oliva_500ml': 'Alimentos y bebidas no alcohólicas',
    'vinagre_500ml': 'Alimentos y bebidas no alcohólicas',
    'azucar_1kg': 'Alimentos y bebidas no alcohólicas',
    'edulcorante_100_sobres': 'Alimentos y bebidas no alcohólicas',
    'sal_1kg': 'Alimentos y bebidas no alcohólicas',
    'sal_gruesa_1kg': 'Alimentos y bebidas no alcohólicas',
    'harina_1kg': 'Alimentos y bebidas no alcohólicas',
    'harina_integral_1kg': 'Alimentos y bebidas no alcohólicas',
    'polenta_500g': 'Alimentos y bebidas no alcohólicas',
    'lentejas_500g': 'Alimentos y bebidas no alcohólicas',
    'porotos_500g': 'Alimentos y bebidas no alcohólicas',
    'garbanzos_500g': 'Alimentos y bebidas no alcohólicas',
    'quinoa_500g': 'Alimentos y bebidas no alcohólicas',
    'mayonesa_250g': 'Alimentos y bebidas no alcohólicas',
    'ketchup_250g': 'Alimentos y bebidas no alcohólicas',
    'mostaza_250g': 'Alimentos y bebidas no alcohólicas',
    'mermelada_454g': 'Alimentos y bebidas no alcohólicas',
    
    # BEBIDAS (15 productos)
    'gaseosa_2L': 'Alimentos y bebidas no alcohólicas',
    'gaseosa_light_2L': 'Alimentos y bebidas no alcohólicas',
    'agua_mineral_2L': 'Alimentos y bebidas no alcohólicas',
    'agua_saborizada_1.5L': 'Alimentos y bebidas no alcohólicas',
    'jugo_1L': 'Alimentos y bebidas no alcohólicas',
    'jugo_concentrado_500ml': 'Alimentos y bebidas no alcohólicas',
    'cafe_250g': 'Alimentos y bebidas no alcohólicas',
    'cafe_instantaneo_170g': 'Alimentos y bebidas no alcohólicas',
    'te_25_saquitos': 'Alimentos y bebidas no alcohólicas',
    'mate_cocido_25_saquitos': 'Alimentos y bebidas no alcohólicas',
    'yerba_mate_1kg': 'Alimentos y bebidas no alcohólicas',
    'leche_coco_400ml': 'Alimentos y bebidas no alcohólicas',
    'bebida_isotonica_500ml': 'Alimentos y bebidas no alcohólicas',
    'energia_drink_250ml': 'Alimentos y bebidas no alcohólicas',
    'soda_1.5L': 'Alimentos y bebidas no alcohólicas',
    
    # ARTÍCULOS DE LIMPIEZA (18 productos)
    'detergente_750ml': 'Otros bienes',
    'detergente_polvo_800g': 'Otros bienes',
    'lavandina_1L': 'Otros bienes',
    'jabon_polvo_800g': 'Otros bienes',
    'suavizante_900ml': 'Otros bienes',
    'limpia_vidrios_500ml': 'Otros bienes',
    'desinfectante_500ml': 'Otros bienes',
    'limpia_pisos_900ml': 'Otros bienes',
    'papel_higienico_4_rollos': 'Otros bienes',
    'papel_cocina_2_rollos': 'Otros bienes',
    'servilletas_100_unidades': 'Otros bienes',
    'pañuelos_descartables_100': 'Otros bienes',
    'bolsas_residuo_10_unidades': 'Otros bienes',
    'esponja_cocina_2_unidades': 'Otros bienes',
    'guantes_latex_100': 'Otros bienes',
    'alcohol_gel_250ml': 'Otros bienes',
    'jabon_liquido_manos_250ml': 'Otros bienes',
    'quitamanchas_500ml': 'Otros bienes',
    
    # ARTÍCULOS DE HIGIENE PERSONAL (20 productos)
    'shampoo_400ml': 'Otros bienes',
    'acondicionador_400ml': 'Otros bienes',
    'jabon_tocador_90g': 'Otros bienes',
    'gel_ducha_400ml': 'Otros bienes',
    'pasta_dental_90g': 'Otros bienes',
    'cepillo_dientes_unidad': 'Otros bienes',
    'enjuague_bucal_250ml': 'Otros bienes',
    'desodorante_150ml': 'Otros bienes',
    'perfume_100ml': 'Otros bienes',
    'crema_corporal_200ml': 'Otros bienes',
    'protector_solar_120ml': 'Otros bienes',
    'toallitas_humedas_80': 'Otros bienes',
    'algodon_100g': 'Otros bienes',
    'hisopo_100_unidades': 'Otros bienes',
    'maquinita_afeitar_3': 'Otros bienes',
    'espuma_afeitar_200ml': 'Otros bienes',
    'after_shave_100ml': 'Otros bienes',
    'talco_100g': 'Otros bienes',
    'crema_manos_75ml': 'Otros bienes',
    'balsamo_labial_4g': 'Otros bienes',
    
    # BEBIDAS ALCOHÓLICAS (12 productos)
    'cerveza_1L': 'Bebidas alcohólicas y tabaco',
    'cerveza_lata_473ml': 'Bebidas alcohólicas y tabaco',
    'cerveza_artesanal_500ml': 'Bebidas alcohólicas y tabaco',
    'vino_750ml': 'Bebidas alcohólicas y tabaco',
    'vino_premium_750ml': 'Bebidas alcohólicas y tabaco',
    'champagne_750ml': 'Bebidas alcohólicas y tabaco',
    'whisky_750ml': 'Bebidas alcohólicas y tabaco',
    'vodka_750ml': 'Bebidas alcohólicas y tabaco',
    'gin_750ml': 'Bebidas alcohólicas y tabaco',
    'fernet_750ml': 'Bebidas alcohólicas y tabaco',
    'aperitivo_750ml': 'Bebidas alcohólicas y tabaco',
    'licor_500ml': 'Bebidas alcohólicas y tabaco',
    
    # PRODUCTOS CONGELADOS (10 productos)
    'helado_1L': 'Alimentos y bebidas no alcohólicas',
    'hamburguesas_congeladas_4': 'Alimentos y bebidas no alcohólicas',
    'papas_fritas_congeladas_1kg': 'Alimentos y bebidas no alcohólicas',
    'pizza_congelada_unidad': 'Alimentos y bebidas no alcohólicas',
    'empanadas_congeladas_12': 'Alimentos y bebidas no alcohólicas',
    'verduras_congeladas_500g': 'Alimentos y bebidas no alcohólicas',
    'pescado_congelado_kg': 'Pescados y mariscos',
    'pollo_congelado_kg': 'Carnes',
    'milanesas_congeladas_kg': 'Carnes',
    'nuggets_pollo_500g': 'Carnes',
    
    # PRODUCTOS PARA BEBÉS (8 productos)
    'pañales_30_unidades': 'Otros bienes',
    'toallitas_bebe_80': 'Otros bienes',
    'leche_formula_800g': 'Leche, lácteos y huevos',
    'papilla_bebe_113g': 'Alimentos y bebidas no alcohólicas',
    'jugo_bebe_200ml': 'Alimentos y bebidas no alcohólicas',
    'shampoo_bebe_400ml': 'Otros bienes',
    'crema_pañal_100g': 'Otros bienes',
    'mamaderas_2_unidades': 'Otros bienes'
}

# Total: 207 productos únicos distribuidos en 12 categorías principales
CATEGORY_COUNT = {
    'Leche, lácteos y huevos': 16,
    'Pan y cereales': 18,
    'Carnes': 23,
    'Pescados y mariscos': 15,
    'Frutas y verduras': 25,
    'Alimentos y bebidas no alcohólicas': 45,
    'Otros bienes': 56,
    'Bebidas alcohólicas y tabaco': 12
}
